### ISSUE TITLE
 IOException occurs in the broker and the number of abnormal brokers exceeded blocking threshold which will affect data writing. Unfortunately, consumers will timeout constantly. 

### ISSUE THREAD

**Issue by Libeibei1990** [Tencent/TubeMQ#138]
IOException occurs in the broker and the number of abnormal brokers exceeded blocking threshold which will affect data writing. Unfortunately, consumers will timeout constantly. 

Broker's internal exception handling caused problems that affect consumption. Consumers should be able to register to the abnormal broker under normal circumstance.

**Comment by gosonzhang** [comment]
Thanks, I'll fix it

**Comment by gosonzhang** [comment]
There is a need to improve the processing logic: if an abnormal disk situation is encountered, during the judgment of the Master, the production and consumer sides should suspend processing of the Broker node, because subsequent production will be rejected by the Broker, so it is necessary to shield the abnormal Broker on the client.

- - - - - - - - - -
这里有一个处理逻辑需要完善：如果遇到磁盘异常情况，在Master进行判断的过程中，生产端和消费端应该对该Broker节点暂停处理，因为后续生产会被拒绝，因此有必要进行对该异常broker在客户端屏蔽处理
